### ISSUE TITLE
Rings not appearing on Debian 9.

### ISSUE THREAD

**Issue by wxguy** [popindavibe/conky-grapes#6]
Followed your install instruction from github main page. The scripts (ring and rc) generated successfully. However, when run using `conky -q -d -c ~/conky/conky-grapes/conky_gen.conkyrc` command, there is no ring visible on the widget. Here is the screenshot grap of my desktop:- 
![desktop-without-rings](https://user-images.githubusercontent.com/9054645/27833205-60c80ed0-60ef-11e7-8630-bae36be8219e.png)

Can you help me to solve this? I am running Debian 9 with up to date package and installed `conky-all` package. Here is the configured files 
[conky-grapes.zip](https://github.com/popindavibe/conky-grapes/files/1122497/conky-grapes.zip)

**Comment by popindavibe** [comment]
Hello, 
Thank you for reaching out. 

First off: if you can, use the gitlab. If you can't, please open an issue about it. The gitlab generally will contain more up to date code. 

Regarding your issue, what is the output when you run the command line without `-q` ?

**Comment by wxguy** [comment]
I will ty to communicate through gitlab in future. As of now, it says my account is locked.

Here is the output of terminal I get when I run without option `q`:-

```
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
conky: llua_do_call: function conky_main execution failed: /home/sundar/conky/conky-grapes/rings-v2_gen.lua:400: attempt to compare number with nil
```

it keeps on going in loop.  After trying out may trials, I found a slution which I think is not the correct one. I had to replace the line  `lua_draw_hook_pre = 'conky_main',` with `lua_draw_hook_pre = 'conky_ring_stats',`. 

Here is the output after solution :- 
```
sundar@localhost:~/conky/conky-grapes$ conky -d -c ~/conky/conky-grapes/conky_gen.conkyrc
conky: desktop window (1200003) is subwindow of root window (c4)
conky: window type - desktop
conky: drawing to created window (0x3400001)
conky: drawing to double buffer
conky: forked to background, pid is 3491
```

Am I doing the correct thing?

**Comment by popindavibe** [comment]
Oh, I see my last mail reply didn't get through... here it goes:

hmm, I myself I'm locked out of Github at present (I'm travelling and forgot to remove the annoying 2-factor auth), I should be back next week.

As for your workaround, it works, right? What you are not getting when bypassing 'conky_main' function is the change of color for the rings if temperature / disk space or battery levels need attention.

Your issue is either with temperature probe or more likely battery, especially if you don't use a laptop. That is something I had not tested, and will be ok on conky side but will break on lua side.

You can also use '-v' when calling the python script and paste the result here to have some sort of dump of what the script detected and how it decided to build the configuration. That should tell us if it is a battery issue or not.

I've updated the gitlab repo, please set your upstream to the master and try again, as this particular issue should now be fixed.

If you get display issue please associate a screenshot and output of the `create_config.py` command with option `-v`

**Comment by wxguy** [comment]
I use laptop with 0 hours battery backup :-)

Here is the log you wanted to see:-

```
Digging in the system to gather info...

INFO: Verbose output.
INFO: Arguments received: Namespace(arch=False, reload=False, rings='blue', text='grey', title='blue', verbose=True)
INFO: Overwriting config file /home/sundar/conky/conky-grapes/rings-v2_gen.lua
INFO: Overwriting config file /home/sundar/conky/conky-grapes/conky_gen.conkyrc
INFO: Number of CPU(s): 4
INFO: Total memory: 3895460 kB
INFO: Free memory: 1289172 kB
INFO: Gateway interface: enp4s0
INFO: Keeping 3 first locally mounted filesystem identified: ['/', '/media/sundar/Data', '/media/sundar/Linux']
INFO: We have 4 CPUs
INFO: We keep 4 CPUs
Writing CPU LUA config in config file
INFO: index_start is 8
Writing FILESYSTEM LUA config in config file
Writing DISK_WATCH lua config in config file
Writing NETWORK LUA config in config file
INFO: We have 4 CPUs
INFO: voffest is set to 3
INFO: We keep 4 CPUs
INFO: adjusting voffset for top cpu processes...
Writing CPU conky config in config file
INFO: adjusting voffset for FS...
Writing FS conky config in config file
Setting up NIC as main interface
Writing NETWORK conky config in config file
INFO: Looking for battery info
WARNING: Could not check battery 0 via /sys/class/power_suplly
WARNING: Could not check battery 0 via acpi
WARNING: Could not check battery 1 via /sys/class/power_suplly
WARNING: Could not check battery 1 via acpi

Success!
New config files have been created:
- /home/sundar/conky/conky-grapes/conky_gen.conkyrc
- /home/sundar/conky/conky-grapes/rings-v2_gen.lua 

If you add a preivous conky-grapes running, the update should be instantaneous. If conky-grapes is not running, you can activate it with following command:
 
conky -q -d -c ~/conky/conky-grapes/conky_gen.conkyrc

 
** If it runs but text is not aligned or font is horribly wrong (and you installed required fonts), chances are you are using a recent version of freetype2 (2.8 onwardsi, see https://bbs.archlinux.org/viewtopic.php?id=226380), which breaks vertical alignment with conky.
If you are on Archlinux, install AUR package https://aur.archlinux.org/packages/freetype2-ttmetrics to fix the vertical alignment (you might need to restart your session / machine for the change to take effect. 
Then call that script again using the --arch option.
```

There is a strange behaviour I have noticed. When  issue the command `conky -q -d -c ~/conky/conky-grapes/conky_gen.conkyrc`, it shows the widget on my desktop. However, it vanishes when I click on the desktop. The widget would never appear even after issue the above command.

Opps I forgot to mention that the above log was created using latest master branch from gitlab. So the problem is not solved.

For your information, I use Debian 9 LXDE with latest updates.

**Comment by popindavibe** [comment]
ok there is no battery detected. I suspect you are getting a different error now. What do you get from the terminal now with:
```
conky -D -c ~/conky/conky-grapes/conky_gen.conkyrc
```

**Comment by popindavibe** [comment]
Also you shouldn't see 'BATTERY' display after your last update.

**Comment by wxguy** [comment]
Sorry for the late reply. Here is what I get when I issue the command `conky -D -c ~/conky/conky-grapes/conky_gen.conkyrc`

```
conky -D -c ~/conky/conky-grapes/conky_gen.conkyrc
DEBUG(0) [/build/conky-H8e3VB/conky-1.10.6/src/conky.cc:2698]: reading contents from config file '/home/sundar/conky/conky-grapes/conky_gen.conkyrc'
DEBUG(0) [/build/conky-H8e3VB/conky-1.10.6/src/x11.cc:497]: Fixed xinerama area to: 0 0 1366 768
DEBUG(0) [/build/conky-H8e3VB/conky-1.10.6/src/x11.cc:497]: Fixed xinerama area to: 0 0 1366 768
conky: desktop window (10002a2) is subwindow of root window (c4)
conky: window type - desktop
conky: drawing to created window (0x2200001)
conky: drawing to double buffer
DEBUG(0) [/build/conky-H8e3VB/conky-1.10.6/src/linux.cc:1235]: parsed hwmon args: '' 'temp' 1 1.000000 0.000000

DEBUG(0) [/build/conky-H8e3VB/conky-1.10.6/src/linux.cc:1235]: parsed hwmon args: '' 'temp' 1 1.000000 0.000000

DEBUG(0) [/build/conky-H8e3VB/conky-1.10.6/src/linux.cc:1235]: parsed hwmon args: '' 'temp' 1 1.000000 0.000000

```

You are correct that there is no batterry display. 

The `click` thing is really pissing me off. I can't see widget if I click on desktop even now. I never experienced this issue in debian 8.

**Comment by wxguy** [comment]
Hey just to inform you that I solved the issue of `click`. Apparently, I am not the only one affected by this issue. I have changed `own_window_type = 'desktop',` to `own_window_type = 'normal'` and changed the line `own_window_hints = 'sticky,skip_taskbar,skip_pager,below',` with  `own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',`.

**Comment by popindavibe** [comment]
Well, I have been playing around with different desktop environment since your previous update. That lead me to change the font size for text fo '8', as '7.5' was not always understood for reasons I don't know.

So I added some commit on gitlab, the resulting conf should be compatible with more systems that way.
About the `own_window_type` and `own_window_hints`, if that fixes it for you I suggest you change it in the `conky_tpl` and you should be all good.
On my side LXDE had no issue displaying the ring, and no disparition (also Debian 9), so I don't know what is the problem here.

So are you getting it all nice and shiny finally?

**Comment by wxguy** [comment]
`So are you getting it all nice and shiny finally?`

After changing the font to 8.5  and changing colours and wallpaper, yes, it looks stunning (a least to my eyes).  Screenshot of my desktop is for your view...

![conky-sample-ss](https://user-images.githubusercontent.com/9054645/28175704-9a8896f6-6812-11e7-8c2e-556ce9124827.png)

You may want to add take away from this issue in to your readme. Also, you may close this issue.

A small suggestion though. The top right corner of the widget looks empty. If possible, you can add some nice text or distro icon(s). But is is just my wish.

**Comment by popindavibe** [comment]
cool! But by changing to 8.5, you are not matching the ring 'entries' anymore... right? At 8 it should have been a good fit. That's mostly the whole idea of the script lol.
Thank you for your feedback anyway. Indeed some kind of icons could fit nicely in here... Have you tried re-generating (you can use just the `-r` option) after shutting down your internet connection by the way? there should be some Easter egg (well, not like it's really hidden anywhere). Would be interesting to know if you get a proper display, as I had to struggle with conky config before managing to display it correctly, and I suspect it might fail on your environment. 

Your LXDE looks MUCH better than my default Debian one by the way.

**Comment by wxguy** [comment]
Here is the screenshot you have requested. I can seem some icons but not sure if it is Easter egg.

![screen-request](https://user-images.githubusercontent.com/9054645/28179196-d5017b3e-681e-11e7-8355-b90750a3c14f.png)


`Your LXDE looks MUCH better than my default Debian one by the way.`

Thanks :-)

**Comment by popindavibe** [comment]
yep, that's it =)
And it displays well apparently, doesn't look like you are hitting transparency issue.

So all good. I'll think on what could be added on top-right. Maybe general load could be useful as well. I'll think about it!
