### ISSUE TITLE
Problem in aligning font in lubuntu 16.04.02

### ISSUE THREAD

**Issue by joaoguariglia** [popindavibe/conky-grapes#8]
Hi, I did all the described procedure but in the end the fonts are breaking what should I do?
I already went to the forum https://bbs.archlinux.org/viewtopic.php?id=226380

But this is no use at all, even because I use Lubuntu

![selecao_001](https://user-images.githubusercontent.com/23190903/36513221-73b729ee-174d-11e8-802d-4455c8e0ef30.png)

**Comment by popindavibe** [comment]
Are you using latest version from the gitlab repo? Can you provide the console output when using the verbose option with create_conky.py?

I haven't tested with LXDE for some time, I'll install and see if I can reproduce the issue.

On 22 February 2018 00:16:57 GMT+00:00, "João Felipe Guariglia" <notifications@github.com> wrote:
>Hi, I did all the described procedure but in the end the fonts are
>breaking what should I do?
>I already went to the forum
>https://bbs.archlinux.org/viewtopic.php?id=226380
>
>But this is no use at all, even because I use Lubuntu
>
>![2018-02-21-211425_1366x768_scrot](https://user-images.githubusercontent.com/23190903/36513079-87e65a62-174c-11e8-8c96-6dd80f5ada10.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/popindavibe/conky-grapes/issues/8

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by joaoguariglia** [comment]
Hi, thanks for the feedback.
Follow the log.


suporte@note-quorum:~/conky/conky-grapes$ ./create_config.py -v
Digging in the system to gather info...

INFO: Verbose output.
INFO: Arguments received: Namespace(arch=False, reload=False, rings='blue', text='grey', title='blue', verbose=True)
INFO: Overwriting config file /home/suporte/conky/conky-grapes/rings-v2_gen.lua
INFO: Overwriting config file /home/suporte/conky/conky-grapes/conky_gen.conkyrc
INFO: Number of CPU(s): 4
INFO: Total memory: 8072208 kB
INFO: Free memory: 6844120 kB
INFO: Gateway interface: enp1s0
INFO: We have 4 CPUs
INFO: We keep 4 CPUs
Writing CPU LUA config in config file
INFO: index_start is 8
Writing FILESYSTEM LUA config in config file
Writing DISK_WATCH lua config in config file
Writing NETWORK LUA config in config file
INFO: We have 4 CPUs
INFO: voffest is set to 2
INFO: We keep 4 CPUs
INFO: adjusting voffset for top cpu processes...
Writing CPU conky config in config file
INFO: voffest is set to 2
Writing IO conky config in config file
INFO: Starting Memory config
memconf = ['${font Michroma:size=10}${color0}${goto 394}${voffset 79}MEMORY\n${font}${goto 324}${voffset -4}${color1}${top_mem name 1}${alignr 40}${top_mem mem 1}%\n', '${goto 324}${color1}${top_mem name 2}${alignr 40}${top_mem mem 2}%\n', '${goto 324}${color1}${top_mem name 3}${alignr 40}${top_mem mem 3}%\n', '${voffset 14}${goto 348}${color1}SWAP${alignr 40}${color1}${swap} / ${color1}${swapmax}\n${voffset 3}${goto 348}${color1}RAM ${alignr 40}${color1}${mem} / ${color1}${memmax}\n']
Writing MEMORY conky config in config file
INFO: adjusting voffset for FS...
Writing FS conky config in config file
Setting up NIC as main interface
Writing NETWORK conky config in config file
INFO: Starting Memory config
Writing TIME conky config in config file
INFO: Looking for battery info
WARNING: Could not check battery 0 via acpi
WARNING: Could not check battery 1 via /sys/class/power_suplly
WARNING: Could not check battery 1 via acpi
Found battery info!
INFO: - Calculating index for battery in lua watch_battery
INFO:   Battery index = 15
INFO: Writing lua BATTERY config in config file
Writing conky BATTERY config in config file

Success!
New config files have been created:
- /home/suporte/conky/conky-grapes/conky_gen.conkyrc
- /home/suporte/conky/conky-grapes/rings-v2_gen.lua 

If you add a preivous conky-grapes running, the update should be instantaneous. If conky-grapes is not running, you can activate it with following command:

conky -q -d -c ~/conky/conky-grapes/conky_gen.conkyrc


** If it runs but text is not aligned or font is horribly wrong (and you installed required fonts), chances are you are using a recent version of freetype2 (2.8 onwards), which breaks vertical alignment with previous conky work. The '--arch' option when creating your conky configuration file should address this.

**Comment by popindavibe** [comment]
I do not see the filesystem info in your output. This is unexpected. What filesystem are you using? 
I tried to reproduce by installing LXDE on my archlinux, it 'displays' fine, if we do not consider the lack of transparency (tried for 20 minutes to get it working, but no luck).
I also tested on XFCE4, it works out of the box.
Let me know about the filesystem, I should probably raise an error when nothing is found.

**Comment by joaoguariglia** [comment]
Thanks for the feedback, so I do not understand you want to see my filesystem?
If so, it follows.

root@note-quorum:~# cat /etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda2 during installation
UUID=55ad9c62-6f75-41ff-b7ea-044f4e6f8ecd /               ext4    errors=remount-ro 0       1
# /boot/efi was on /dev/sda1 during installation
UUID=6667-F826  /boot/efi       vfat    umask=0077      0       1
# swap was on /dev/sda3 during installation
UUID=45a20339-a717-4e27-a9a0-55c0fca76f4e none            swap    sw              0       0
root@note-quorum:~#

**Comment by popindavibe** [comment]
Hmm, I don't understand why your fs are not detected. Could you paste the output for `cat /proc/mounts`? 

I'll run the code against it, but I have deployed the script against several distribution/filesystem types without issues...


On 22 February 2018 21:02:00 GMT+00:00, "João Felipe Guariglia" <notifications@github.com> wrote:
>Thanks for the feedback, so I do not understand you want to see my
>filesystem?
>If so, it follows.
>
>root@note-quorum:~# cat /etc/fstab
># /etc/fstab: static file system information.
>#
># Use 'blkid' to print the universally unique identifier for a
># device; this may be used with UUID= as a more robust way to name
>devices
># that works even if disks are added and removed. See fstab(5).
>#
># <file system> <mount point>   <type>  <options>       <dump>  <pass>
># / was on /dev/sda2 during installation
>UUID=55ad9c62-6f75-41ff-b7ea-044f4e6f8ecd /               ext4   
>errors=remount-ro 0       1
># /boot/efi was on /dev/sda1 during installation
>UUID=6667-F826  /boot/efi       vfat    umask=0077      0       1
># swap was on /dev/sda3 during installation
>UUID=45a20339-a717-4e27-a9a0-55c0fca76f4e none            swap    sw   
>          0       0
>root@note-quorum:~# 
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/popindavibe/conky-grapes/issues/8#issuecomment-367820845

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by joaoguariglia** [comment]
Thanks for the feedback, just remembering that I got your code in github, would it be ideal?

Follow the status


 cat /proc/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=4009732k,nr_inodes=1002433,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=807224k,mode=755 0 0
/dev/sda2 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=24,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=449 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
/dev/sda1 /boot/efi vfat rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=807224k,mode=700,uid=1000,gid=1000 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0

**Comment by popindavibe** [comment]
No best is to get it from gitlab, as synchronisation between the two is not always working. The 'original' repo is on gitlab.nomagic.uk (see Readme) 

I'll see if I can explain current issue from your output, in the meantime I suggest you get the latest version from master on gitlab.

On 26 February 2018 12:08:33 GMT+00:00, "João Felipe Guariglia" <notifications@github.com> wrote:
>Thanks for the feedback, just remembering that I got your code in
>github, would it be ideal?
>
>Follow the status
>
>
> cat /proc/mounts
>sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
>proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
>udev /dev devtmpfs
>rw,nosuid,relatime,size=4009732k,nr_inodes=1002433,mode=755 0 0
>devpts /dev/pts devpts
>rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
>tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=807224k,mode=755 0 0
>/dev/sda2 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
>securityfs /sys/kernel/security securityfs
>rw,nosuid,nodev,noexec,relatime 0 0
>tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
>tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
>tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
>cgroup /sys/fs/cgroup/systemd cgroup
>rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
>0 0
>pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
>efivarfs /sys/firmware/efi/efivars efivarfs
>rw,nosuid,nodev,noexec,relatime 0 0
>cgroup /sys/fs/cgroup/cpu,cpuacct cgroup
>rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
>cgroup /sys/fs/cgroup/blkio cgroup
>rw,nosuid,nodev,noexec,relatime,blkio 0 0
>cgroup /sys/fs/cgroup/memory cgroup
>rw,nosuid,nodev,noexec,relatime,memory 0 0
>cgroup /sys/fs/cgroup/perf_event cgroup
>rw,nosuid,nodev,noexec,relatime,perf_event 0 0
>cgroup /sys/fs/cgroup/net_cls,net_prio cgroup
>rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
>cgroup /sys/fs/cgroup/hugetlb cgroup
>rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
>cgroup /sys/fs/cgroup/cpuset cgroup
>rw,nosuid,nodev,noexec,relatime,cpuset 0 0
>cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma
>0 0
>cgroup /sys/fs/cgroup/devices cgroup
>rw,nosuid,nodev,noexec,relatime,devices 0 0
>cgroup /sys/fs/cgroup/freezer cgroup
>rw,nosuid,nodev,noexec,relatime,freezer 0 0
>cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids
>0 0
>systemd-1 /proc/sys/fs/binfmt_misc autofs
>rw,relatime,fd=24,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=449
>0 0
>debugfs /sys/kernel/debug debugfs rw,relatime 0 0
>hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
>mqueue /dev/mqueue mqueue rw,relatime 0 0
>fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
>configfs /sys/kernel/config configfs rw,relatime 0 0
>/dev/sda1 /boot/efi vfat
>rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro
>0 0
>tmpfs /run/user/1000 tmpfs
>rw,nosuid,nodev,relatime,size=807224k,mode=700,uid=1000,gid=1000 0 0
>gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse
>rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/popindavibe/conky-grapes/issues/8#issuecomment-368480184

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by joaoguariglia** [comment]
Good Morning,
For gitlab it worked very well!
Thank you for your support! It was very beautiful.
![fundo](https://user-images.githubusercontent.com/23190903/36728627-2ab5cc6c-1ba0-11e8-9c4f-aed55994dac5.png)

**Comment by popindavibe** [comment]
Cool! The alignment is a bit off though, which shouldn't happen. Also I suggest you remove the screenshot as it shows public IP(!).

Otherwise everything shows, so that's good. I wonder why the misalignment though... This was generated without the `--arch`, right?

**Comment by joaoguariglia** [comment]
I saw it only after it got crooked, but now I already did not have the --archlinux inserted
Look how beautiful it was :)

![selecao_004](https://user-images.githubusercontent.com/23190903/36745272-b9cb9fda-1bcd-11e8-90a7-cec94ac44c77.png)

**Comment by popindavibe** [comment]
Nice! This is more like it 😉
Glad you got it working. Enjoy!
